# from matplotlib's azure setup


schedules:
- cron: "0 0 * * 4"
  displayName: Weekly build
  branches:
    include:
    - releases/*
  always: true


trigger:
  tags:
    include:
    - '*'
  branches:
    include:
    - '*'


variables:
  PIP_CACHE_DIR: $(Pipeline.Workspace)/cache/pip


jobs:
- job: 'static_checks'
  pool:
    vmImage: ubuntu-22.04
  variables:
    TOXENV: flake8,pylint,docs,doctest,check-manifest,checkreadme
  steps:
    - task: UsePythonVersion@0
      inputs:
        versionSpec: '3.12'
        architecture: 'x64'
    - script: |
        pip install tox
      displayName: Install tox
    - script: |
        tox
      displayName: tox

- job: 'ubuntu'
  pool:
    vmImage: ubuntu-22.04
  strategy:
    matrix:
      py37:
        python.version: '3.7'
        TOXENV: py37
      py38:
        python.version: '3.8'
        TOXENV: py38
      py39:
        python.version: '3.9'
        TOXENV: py39
      py310:
        python.version: '3.10'
        TOXENV: py310
      py311:
        python.version: '3.11'
        TOXENV: py311
      py312:
        python.version: '3.12'
        TOXENV: py312

  steps:
    - template: ci/azure-pipelines-steps.yml
      parameters:
        platform: linux
