status = [
  "ci/circleci: pylint",
  "ci/circleci: py37",
  "ci/circleci: flake8",
  "ci/circleci: checkreadme",
  "ci/circleci: check-manifest",
  "continuous-integration/appveyor/branch",
  "codecov/patch",
  "codecov/project",
]
timeout_sec = 7200
